// Workout splits configuration and exercise data
// Modeled after the "Arms in 60" structure and expanded for Chest, Shoulders, Back, and Legs

export const WORKOUT_SPLITS = [
  {
    id: "arms",
    name: "Arms in 60",
    title: "Arms in 60",
    subtitle: "Bicep & Tricep Timer",
    badge: "Arms Split",
    focus: "Biceps · Triceps · Forearms",
    color: "#FF5C3E",
    bgTint: "rgba(255, 92, 62, 0.08)",
    borderTint: "rgba(255, 92, 62, 0.25)",
    estimatedMin: 56,
    setsPerExercise: 5,
    workSec: 66,
    restBetweenSets: 60,
    restBetweenExercises: 60,
    warmupSec: 300,
    warmupCue: "Arm circles, band pull-aparts, light curls — get blood into the biceps and triceps",
    cooldownSec: 180,
    cooldownCue: "Cross-body tricep stretch + bicep wall stretch, ~30s per side",
    exercises: [
      {
        id: "standing_db_curl",
        name: "Standing Dumbbell Curl",
        muscle: "bicep",
        tag: "bicep",
        cue: "Elbows pinned to your sides, squeeze at the top",
        defaultLoad: 14,
      },
      {
        id: "overhead_tricep_ext",
        name: "Overhead Tricep Extension",
        muscle: "tricep",
        tag: "tricep",
        cue: "One dumbbell, elbows pointed forward, full stretch",
        defaultLoad: 20,
      },
      {
        id: "hammer_curl",
        name: "Hammer Curl",
        muscle: "bicep",
        tag: "bicep",
        cue: "Neutral grip, controlled on the way down",
        defaultLoad: 16,
      },
      {
        id: "bench_dips",
        name: "Bench Dips",
        muscle: "tricep",
        tag: "tricep",
        cue: "Feet out, lower until elbows hit 90°",
        defaultLoad: 0, // bodyweight or added plate
      },
      {
        id: "concentration_curl",
        name: "Concentration Curl",
        muscle: "bicep",
        tag: "bicep",
        cue: "Elbow braced on your thigh, slow and strict",
        defaultLoad: 12,
      },
      {
        id: "close_grip_pushup",
        name: "Close-Grip Push-Up",
        muscle: "tricep",
        tag: "tricep",
        cue: "Hands under shoulders, elbows tucked in",
        defaultLoad: 0,
      },
      {
        id: "zottman_curl",
        name: "Zottman Curl",
        muscle: "bicep",
        tag: "bicep",
        cue: "Curl up palms-up, rotate, lower palms-down",
        defaultLoad: 12,
      },
      {
        id: "skull_crusher",
        name: "Skull Crusher",
        muscle: "tricep",
        tag: "tricep",
        cue: "Elbows fixed, lower to forehead, press up",
        defaultLoad: 22.5,
      },
    ],
  },
  {
    id: "chest",
    name: "Chest in 60",
    title: "Chest in 60",
    subtitle: "Pec Power & Hypertrophy",
    badge: "Chest Split",
    focus: "Upper Chest · Mid Pecs · Lower Pecs",
    color: "#2F745C",
    bgTint: "rgba(47, 116, 92, 0.08)",
    borderTint: "rgba(47, 116, 92, 0.25)",
    estimatedMin: 56,
    setsPerExercise: 5,
    workSec: 66,
    restBetweenSets: 60,
    restBetweenExercises: 60,
    warmupSec: 300,
    warmupCue: "Scapular push-ups, light band flyes, arm rotations — activate the anterior chain",
    cooldownSec: 180,
    cooldownCue: "Doorway pec stretch and chest openers, breathing deeply into ribcage",
    exercises: [
      {
        id: "incline_db_press",
        name: "Incline Dumbbell Press",
        muscle: "upper chest",
        tag: "chest",
        cue: "Bench at 30°, press up and slightly inward, full stretch at the bottom",
        defaultLoad: 24,
      },
      {
        id: "flat_bench_press",
        name: "Flat Dumbbell Bench Press",
        muscle: "mid chest",
        tag: "chest",
        cue: "Scapula retracted, drive through the chest, controlled 2s descent",
        defaultLoad: 26,
      },
      {
        id: "incline_db_flyes",
        name: "Incline Dumbbell Flyes",
        muscle: "upper chest",
        tag: "chest",
        cue: "Slight elbow bend, hug an imaginary barrel, peak squeeze at apex",
        defaultLoad: 14,
      },
      {
        id: "chest_dips",
        name: "Parallel Bar Chest Dips",
        muscle: "lower chest",
        tag: "chest",
        cue: "Lean torso 30° forward, elbows slightly flared, descend to 90°",
        defaultLoad: 0,
      },
      {
        id: "hex_press",
        name: "Incline Dumbbell Hex Press",
        muscle: "inner chest",
        tag: "chest",
        cue: "Squeeze dumbbells together continuously while pressing up and down",
        defaultLoad: 18,
      },
      {
        id: "deficit_pushups",
        name: "Deficit Push-Up",
        muscle: "mid chest",
        tag: "chest",
        cue: "Hands on dumbbells or plates for deep range of motion, locked core",
        defaultLoad: 0,
      },
      {
        id: "standing_cable_flyes",
        name: "Cable Crossover / Low Flye",
        muscle: "lower chest",
        tag: "chest",
        cue: "Sweep arms forward and down, crossover slightly for peak contraction",
        defaultLoad: 12.5,
      },
      {
        id: "diamond_pushup",
        name: "Diamond Push-Up Finisher",
        muscle: "inner pec",
        tag: "chest",
        cue: "Hands touch in diamond shape, elbows tucked, explosive lockout",
        defaultLoad: 0,
      },
    ],
  },
  {
    id: "shoulders",
    name: "Shoulders in 60",
    title: "Shoulders in 60",
    subtitle: "Complete 3D Delt Builder",
    badge: "Shoulders Split",
    focus: "Side Delts · Front Delts · Rear Delts · Traps",
    color: "#8B7CF6",
    bgTint: "rgba(139, 124, 246, 0.08)",
    borderTint: "rgba(139, 124, 246, 0.25)",
    estimatedMin: 56,
    setsPerExercise: 5,
    workSec: 66,
    restBetweenSets: 60,
    restBetweenExercises: 60,
    warmupSec: 300,
    warmupCue: "Band face-pulls, shoulder dislocations, light halos to lubricate the shoulder joint",
    cooldownSec: 180,
    cooldownCue: "Rear delt cross-body stretch and overhead tricep/lat reach",
    exercises: [
      {
        id: "seated_db_press",
        name: "Seated Overhead Dumbbell Press",
        muscle: "front delt",
        tag: "shoulder",
        cue: "Brace your core, press overhead in a natural arc, avoid arched lower back",
        defaultLoad: 20,
      },
      {
        id: "lateral_raises",
        name: "Dumbbell Lateral Raise",
        muscle: "side delt",
        tag: "shoulder",
        cue: "Lead with elbows, slight forward hinge, pause 1s at parallel",
        defaultLoad: 10,
      },
      {
        id: "face_pulls",
        name: "Rope Face Pull",
        muscle: "rear delt",
        tag: "shoulder",
        cue: "Pull to eye level, pull rope apart at the top, externally rotate",
        defaultLoad: 17.5,
      },
      {
        id: "arnold_press",
        name: "Arnold Press",
        muscle: "front & side delt",
        tag: "shoulder",
        cue: "Start palms-in at chin, rotate outward as you drive up overhead",
        defaultLoad: 16,
      },
      {
        id: "rear_delt_flyes",
        name: "Incline Bench Rear Delt Flye",
        muscle: "rear delt",
        tag: "shoulder",
        cue: "Chest against 45° incline bench, pinkies high, isolate rear delts",
        defaultLoad: 8,
      },
      {
        id: "front_raises",
        name: "Neutral-Grip Dumbbell Front Raise",
        muscle: "front delt",
        tag: "shoulder",
        cue: "Strict cadence without body swing, raise to eye level with control",
        defaultLoad: 10,
      },
      {
        id: "cable_lateral_raise",
        name: "Lean-Away Lateral Raise",
        muscle: "side delt",
        tag: "shoulder",
        cue: "Constant tension from the bottom of the movement, 3s eccentric",
        defaultLoad: 7.5,
      },
      {
        id: "db_shrugs",
        name: "Dumbbell Shrug & Hold",
        muscle: "upper traps",
        tag: "shoulder",
        cue: "Elevate straight up toward ears, hold isometric peak for 2 counts",
        defaultLoad: 26,
      },
    ],
  },
  {
    id: "back",
    name: "Back in 60",
    title: "Back in 60",
    subtitle: "V-Taper & Back Thickness",
    badge: "Back Split",
    focus: "Lats · Rhomboids · Mid Back · Spinal Erectors",
    color: "#0284C7",
    bgTint: "rgba(2, 132, 199, 0.08)",
    borderTint: "rgba(2, 132, 199, 0.25)",
    estimatedMin: 56,
    setsPerExercise: 5,
    workSec: 66,
    restBetweenSets: 60,
    restBetweenExercises: 60,
    warmupSec: 300,
    warmupCue: "Cat-cow stretches, thoracic extensions, dead hangs to decompress the spine",
    cooldownSec: 180,
    cooldownCue: "Child's pose and lat hang stretch, breathing deeply into lower back",
    exercises: [
      {
        id: "lat_pulldown",
        name: "Wide-Grip Lat Pulldown",
        muscle: "lats width",
        tag: "back",
        cue: "Drive elbows down to pockets, lead with sternum, full stretch at top",
        defaultLoad: 50,
      },
      {
        id: "bent_over_row",
        name: "Bent-Over Barbell Row",
        muscle: "mid back",
        tag: "back",
        cue: "Hinge at 45°, pull bar into navel, retract shoulder blades firmly",
        defaultLoad: 45,
      },
      {
        id: "seated_cable_row",
        name: "Seated Cable Row (Neutral Grip)",
        muscle: "rhomboids & lats",
        tag: "back",
        cue: "Chest proud, pull handles into ribs without rocking torso",
        defaultLoad: 45,
      },
      {
        id: "single_arm_db_row",
        name: "Single-Arm Dumbbell Row",
        muscle: "lat thickness",
        tag: "back",
        cue: "Pull dumbbell toward hip crease, keep elbow tight, full lat stretch",
        defaultLoad: 26,
      },
      {
        id: "straight_arm_pulldown",
        name: "Straight-Arm Lat Pulldown",
        muscle: "lat isolation",
        tag: "back",
        cue: "Slight forward lean, sweep rope in an arc down to thighs, hold 1s",
        defaultLoad: 20,
      },
      {
        id: "chest_supported_row",
        name: "Incline Chest-Supported Row",
        muscle: "upper back",
        tag: "back",
        cue: "Elbows out at 60°, squeeze blades together, eliminates lower back strain",
        defaultLoad: 20,
      },
      {
        id: "db_pullover",
        name: "Dumbbell Lat Pullover",
        muscle: "serratus & lats",
        tag: "back",
        cue: "Lie across bench, deep stretch over head, pull with lats to chest line",
        defaultLoad: 22,
      },
      {
        id: "back_hyperextension",
        name: "Back Hyperextension / Hinge",
        muscle: "erectors",
        tag: "back",
        cue: "Hinge at hips, rise to straight alignment, squeeze glutes and spinal erectors",
        defaultLoad: 10,
      },
    ],
  },
  {
    id: "legs",
    name: "Legs in 60",
    title: "Legs & Core in 60",
    subtitle: "Lower Body Power & Stability",
    badge: "Legs Split",
    focus: "Quads · Hamstrings · Glutes · Calves · Core",
    color: "#D97706",
    bgTint: "rgba(217, 119, 6, 0.08)",
    borderTint: "rgba(217, 119, 6, 0.25)",
    estimatedMin: 56,
    setsPerExercise: 5,
    workSec: 66,
    restBetweenSets: 60,
    restBetweenExercises: 60,
    warmupSec: 300,
    warmupCue: "Bodyweight air squats, hip openers, glute bridges, leg swings",
    cooldownSec: 180,
    cooldownCue: "Pigeon pose, kneeling quad stretch, seated hamstring reach",
    exercises: [
      {
        id: "goblet_squat",
        name: "Goblet / Barbell Back Squat",
        muscle: "quads & glutes",
        tag: "legs",
        cue: "Chest upright, break parallel, drive through midfoot on the ascent",
        defaultLoad: 40,
      },
      {
        id: "romanian_deadlift",
        name: "Dumbbell Romanian Deadlift",
        muscle: "hamstrings",
        tag: "legs",
        cue: "Hinge hips back with soft knees, feel deep hamstring stretch, neutral spine",
        defaultLoad: 30,
      },
      {
        id: "bulgarian_split_squat",
        name: "Bulgarian Split Squat",
        muscle: "glutes & quads",
        tag: "legs",
        cue: "Rear foot on bench, sink straight down, push through front heel",
        defaultLoad: 16,
      },
      {
        id: "standing_calf_raise",
        name: "Standing Dumbbell Calf Raise",
        muscle: "calves",
        tag: "legs",
        cue: "Full deep stretch at bottom, explode onto balls of feet, 1s isometric hold",
        defaultLoad: 24,
      },
      {
        id: "walking_lunges",
        name: "Dumbbell Walking Lunges",
        muscle: "quads & glutes",
        tag: "legs",
        cue: "Smooth steps, 90° angles on both knees, keep torso proud",
        defaultLoad: 18,
      },
      {
        id: "lying_leg_curl",
        name: "Hamstring Curl / Nordic Negative",
        muscle: "hamstrings",
        tag: "legs",
        cue: "Slow 3s negative, curl heels toward glutes without lifting hips",
        defaultLoad: 35,
      },
      {
        id: "hanging_knee_raise",
        name: "Hanging Knee / Leg Raise",
        muscle: "lower abs",
        tag: "core",
        cue: "Tuck pelvis up, curl knees into chest, eliminate all swinging",
        defaultLoad: 0,
      },
      {
        id: "plank_tap",
        name: "Plank with Shoulder Tap",
        muscle: "deep core",
        tag: "core",
        cue: "Feet shoulder-width, lock hips totally flat to ground, tap opposite shoulder",
        defaultLoad: 0,
      },
    ],
  },
];
